### ISSUE TITLE
Install only packages that aren't already installed

### ISSUE THREAD

**Issue by jdreimann** [mikefrey/node-pac#14]
Currently `pac install` seems to unpack and install all packages, regardless of whether they are already installed. I think that pac should optionally only install new or different packages, as judged by the version in the package.json.

**Comment by mikefrey** [comment]
I don't really see a use case when you would need to only install packages that are not already installed. Is it for speed? Or to prevent installing over something that has been customized?

**Comment by jdreimann** [comment]
It's for speed. In our build environment it takes ~5 minutes to install all npm dependencies, while the actual build takes less than a minute. We only update dependencies once every two or three weeks. We have hundreds of unnecessarily slow builds in between, because we run `pac install` on every build to make sure that we have all the correct dependencies.
Manually updating dependencies on our build environment would solve the issue on the surface but would make our process less automated.

**Comment by mikefrey** [comment]
`pac install` really only decompresses the files in the `.module` directory. Is it really that process that is taking 5 min? or is it the subsequent `npm rebuild`?

**Comment by jdreimann** [comment]
You're right, it's the rebuild that takes that long. We've solved the problem by checking whether the module directory has changed since the last successful build in our build script, and only ```pac install``` and ```npm rebuild``` if so.
