### ISSUE TITLE
OSX -> Ubuntu tar issues

### ISSUE THREAD

**Issue by brycefisher** [mikefrey/node-pac#16]
Dear @mikefrey,

You are amazing. This module rocks my face. 

Sadly, gnu-tar and bsd-tar do not rock my face. We're using `tar -zxf` as a npm run-script to "unpac" our ./modules/*.tgz during our deploy. 

The problem is that so many warnings are thrown by Ubuntu's gnutar about unknown headers, that it creates a lot of noise in our console during the deploy. In fact, so much memory is used to display these warnings that our socket's stderr maxBuffer is exceeded and our deployments crash.

![Ignoring unknown extended header keyword errors that go on for thousands of lines](https://cloud.githubusercontent.com/assets/220106/8221210/4d6035c0-1510-11e5-812b-8e48c583c597.png)

As a quickfix, [we're using the (gnu-tar only) flag `--warning=no-unknown-keyword`]( http://superuser.com/questions/318809/linux-os-x-tar-incompatibility-tarballs-created-on-os-x-give-errors-when-unt/688231#688231), but it this means other developers will either have to use a different npm run script (duplication, training, and maintenance overhead), OR we'll have to make the script compatible across various OSes. We'd love to dockerize, but its tough to get the runway for this.

The ideal solution, however, would be to *not* include the extended header keywords in the first place. Then both gnu-tar and bsd-tar could extract the files without complaining. I tried just setting an environment flag as `COPYFILE_DISABLE=1`, but that didn't seem to stop the headers from appearing :'(

**Comment by mikefrey** [comment]
@brycefisher pac doesn't use OSX's `tar` command. It uses a pure JS tar implementation: https://www.npmjs.com/package/tar

I'm not sure there is a way to disable extended header keywords in node-tar. If you find a way, I'd be happy to accept a PR fixing it.

**Comment by brycefisher** [comment]
Cool! I'll reach out to that module maintainer. Thanks for your help!
